<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HmoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hmos = [
            [
                'hmo_name' => 'Hygeia HMO Limited',
                'contact_person' => 'Dr. Funmi Adewale',
                'phone' => '08012345678',
                'email' => 'info@hygeiahmo.com',
                'address' => '23, Idowu Martins Street, Victoria Island, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Avon Healthcare Limited',
                'contact_person' => 'Mr. Chukwudi Okafor',
                'phone' => '08023456789',
                'email' => 'contact@avonhealthcare.com',
                'address' => '11A, Jimoh Odutola Street, Off Eric Moore Road, Surulere, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Total Health Trust Limited',
                'contact_person' => 'Mrs. Blessing Nnamdi',
                'phone' => '08034567890',
                'email' => 'info@totalhealthtrust.com',
                'address' => 'Plot 293B, Akin Olugbade Street, Victoria Island, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Clearline International Limited',
                'contact_person' => 'Dr. Ahmed Musa',
                'phone' => '08045678901',
                'email' => 'support@clearlinehmo.com',
                'address' => '5, Ogunsiji Close, Off Allen Avenue, Ikeja, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Aiico Multishield',
                'contact_person' => 'Mr. Tunde Bakare',
                'phone' => '08056789012',
                'email' => 'info@aiico.com',
                'address' => 'AIICO Plaza, Plot 2, Oba Akran Avenue, Ikeja, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Redcare Health Limited',
                'contact_person' => 'Mrs. Grace Obioma',
                'phone' => '08067890123',
                'email' => 'hello@redcarehmo.com',
                'address' => '12B, Ladipo Kasumu Street, Ikeja GRA, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Greenlife Pharmacy Limited',
                'contact_person' => 'Pharm. Emeka Eze',
                'phone' => '08078901234',
                'email' => 'care@greenlifehmo.com',
                'address' => '67, Opebi Road, Ikeja, Lagos',
                'status' => 'Inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Healthcare International Limited',
                'contact_person' => 'Dr. Fatima Bello',
                'phone' => '08089012345',
                'email' => 'info@healthcareinternational.com',
                'address' => '3rd Floor, Mulliner Towers, 39 Alfred Rewane Road, Ikoyi, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Mediplan Healthcare Limited',
                'contact_person' => 'Mr. Olumide Oladipo',
                'phone' => '08090234567',
                'email' => 'info@mediplanhealthcare.com',
                'address' => '21, Mobolaji Bank Anthony Way, Ikeja, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Integrated Healthcare Limited',
                'contact_person' => 'Mrs. Nneka Ezeugo',
                'phone' => '08101345678',
                'email' => 'contact@integratedhealthcare.com',
                'address' => '54, Isaac John Street, GRA Ikeja, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Premier Health Management Services',
                'contact_person' => 'Dr. Yusuf Kazeem',
                'phone' => '08112456789',
                'email' => 'info@premierhms.com',
                'address' => '18, Ligali Ayorinde Street, Victoria Island, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Novo Health Africa',
                'contact_person' => 'Mrs. Chioma Nwankwo',
                'phone' => '08123567890',
                'email' => 'hello@novohealthafrica.com',
                'address' => 'Block B, Plot 9, Nurudeen Olowopopo Drive, Ikeja, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Reliance HMO',
                'contact_person' => 'Mr. Akin Solarin',
                'phone' => '08134678901',
                'email' => 'support@reliancehmo.com',
                'address' => '32, Lewis Street, Lagos Island, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Phoenix Health Plans',
                'contact_person' => 'Dr. Adebisi Salami',
                'phone' => '08145789012',
                'email' => 'info@phoenixhealthplans.com',
                'address' => '87, Awolowo Road, Ikoyi, Lagos',
                'status' => 'Inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Medicare Health Plans Limited',
                'contact_person' => 'Mrs. Kemi Johnson',
                'phone' => '08156890123',
                'email' => 'care@medicarehealthplans.com',
                'address' => '45, Admiralty Way, Lekki Phase 1, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Oceanic Health Management',
                'contact_person' => 'Mr. Ibrahim Tijani',
                'phone' => '08167901234',
                'email' => 'info@oceanichealthmgt.com',
                'address' => '76, Oregun Road, Oregun, Ikeja, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Wellness HMO Limited',
                'contact_person' => 'Dr. Ngozi Obi',
                'phone' => '08178012345',
                'email' => 'hello@wellnesshmo.com',
                'address' => '14, Broad Street, Lagos Island, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Anchorage Health HMO',
                'contact_person' => 'Mr. Segun Adeyinka',
                'phone' => '08189123456',
                'email' => 'contact@anchoragehmo.com',
                'address' => '22, Creek Road, Apapa, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'United Healthcare International',
                'contact_person' => 'Mrs. Hauwa Abdullahi',
                'phone' => '08190234567',
                'email' => 'info@unitedhealthcare.ng',
                'address' => '9, Adeola Hopewell Street, Victoria Island, Lagos',
                'status' => 'Inactive',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hmo_name' => 'Diamond Health Care Services',
                'contact_person' => 'Dr. Victor Onyema',
                'phone' => '08101345679',
                'email' => 'support@diamondhealthcare.com',
                'address' => '38, Bode Thomas Street, Surulere, Lagos',
                'status' => 'Active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('hmos')->insert($hmos);
    }
}