<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patients = [
            [
                'card_number' => 'EMS-2024-0001',
                'patient_lastname' => 'Adeyemi',
                'patient_firstname' => 'Oluwaseun',
                'patient_phone' => '08012345678',
                'patient_occupation' => 'Software Engineer',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1985-03-15',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Hygeia HMO Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '15, Adeniyi Jones Avenue, Ikeja, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Adeyemi Folake',
                'kin_relationship' => 'Spouse',
                'patient_kin_phone' => '08098765432',
                'patient_kin_address' => '15, Adeniyi Jones Avenue, Ikeja, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0002',
                'patient_lastname' => 'Okonkwo',
                'patient_firstname' => 'Chidinma',
                'patient_phone' => '08123456789',
                'patient_occupation' => 'Teacher',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1990-07-22',
                'patient_type' => 'Private',
                'patient_hmo' => null,
                'patient_nationality' => 'Nigerian',
                'patient_address' => '42, Ago Palace Way, Okota, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Okonkwo Emeka',
                'kin_relationship' => 'Husband',
                'patient_kin_phone' => '08087654321',
                'patient_kin_address' => '42, Ago Palace Way, Okota, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0003',
                'patient_lastname' => 'Ibrahim',
                'patient_firstname' => 'Abubakar',
                'patient_phone' => '08034567890',
                'patient_occupation' => 'Business Owner',
                'patient_religion' => 'Islam',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1978-11-05',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Total Health Trust Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '8, Adeniran Ogunsanya Street, Surulere, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Ibrahim Zainab',
                'kin_relationship' => 'Wife',
                'patient_kin_phone' => '08076543210',
                'patient_kin_address' => '8, Adeniran Ogunsanya Street, Surulere, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0004',
                'patient_lastname' => 'Williams',
                'patient_firstname' => 'Joy',
                'patient_phone' => '08145678901',
                'patient_occupation' => 'Nurse',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1995-02-14',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Avon Healthcare Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '23, Oluwole Street, Apapa, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Williams Emmanuel',
                'kin_relationship' => 'Father',
                'patient_kin_phone' => '08065432109',
                'patient_kin_address' => '23, Oluwole Street, Apapa, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0005',
                'patient_lastname' => 'Bello',
                'patient_firstname' => 'Muhammad',
                'patient_phone' => '08056789012',
                'patient_occupation' => 'Civil Servant',
                'patient_religion' => 'Islam',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1982-09-30',
                'patient_type' => 'Retainership',
                'patient_hmo' => null,
                'patient_nationality' => 'Nigerian',
                'patient_address' => '56, Ikorodu Road, Jibowu, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Bello Halima',
                'kin_relationship' => 'Spouse',
                'patient_kin_phone' => '08054321098',
                'patient_kin_address' => '56, Ikorodu Road, Jibowu, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0006',
                'patient_lastname' => 'Nwosu',
                'patient_firstname' => 'Amara',
                'patient_phone' => '08167890123',
                'patient_occupation' => 'Accountant',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1988-06-18',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Clearline International Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '31, Allen Avenue, Ikeja, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Nwosu Chinedu',
                'kin_relationship' => 'Brother',
                'patient_kin_phone' => '08043210987',
                'patient_kin_address' => '31, Allen Avenue, Ikeja, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0007',
                'patient_lastname' => 'Adebayo',
                'patient_firstname' => 'Tunde',
                'patient_phone' => '08078901234',
                'patient_occupation' => 'Lawyer',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1975-12-10',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Aiico Multishield',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '12, Victoria Island Extension, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Adebayo Kehinde',
                'kin_relationship' => 'Wife',
                'patient_kin_phone' => '08032109876',
                'patient_kin_address' => '12, Victoria Island Extension, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0008',
                'patient_lastname' => 'Eze',
                'patient_firstname' => 'Blessing',
                'patient_phone' => '08189012345',
                'patient_occupation' => 'Entrepreneur',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1992-04-25',
                'patient_type' => 'Private',
                'patient_hmo' => null,
                'patient_nationality' => 'Nigerian',
                'patient_address' => '67, Lekki Phase 1, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Eze Chukwuma',
                'kin_relationship' => 'Husband',
                'patient_kin_phone' => '08021098765',
                'patient_kin_address' => '67, Lekki Phase 1, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0009',
                'patient_lastname' => 'Yusuf',
                'patient_firstname' => 'Hassan',
                'patient_phone' => '08090123456',
                'patient_occupation' => 'Doctor',
                'patient_religion' => 'Islam',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1980-08-12',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Redcare Health Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '45, Ketu-Alapere Road, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Yusuf Amina',
                'kin_relationship' => 'Spouse',
                'patient_kin_phone' => '08010987654',
                'patient_kin_address' => '45, Ketu-Alapere Road, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0010',
                'patient_lastname' => 'Okeke',
                'patient_firstname' => 'Grace',
                'patient_phone' => '08101234567',
                'patient_occupation' => 'Pharmacist',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1987-01-20',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Healthcare International Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '19, Maryland Mall Road, Ikeja, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Okeke Ifeanyi',
                'kin_relationship' => 'Husband',
                'patient_kin_phone' => '08109876543',
                'patient_kin_address' => '19, Maryland Mall Road, Ikeja, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0011',
                'patient_lastname' => 'Oluwole',
                'patient_firstname' => 'Funmilayo',
                'patient_phone' => '08112345678',
                'patient_occupation' => 'Banker',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1993-05-08',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Mediplan Healthcare Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '28, Awolowo Way, Ikeja, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Oluwole Abosede',
                'kin_relationship' => 'Mother',
                'patient_kin_phone' => '08020987654',
                'patient_kin_address' => '28, Awolowo Way, Ikeja, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0012',
                'patient_lastname' => 'Oladipo',
                'patient_firstname' => 'Babatunde',
                'patient_phone' => '08123456780',
                'patient_occupation' => 'Engineer',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1979-11-30',
                'patient_type' => 'Pre-Medical',
                'patient_hmo' => null,
                'patient_nationality' => 'Nigerian',
                'patient_address' => '14, Gbagada Expressway, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Oladipo Mojisola',
                'kin_relationship' => 'Wife',
                'patient_kin_phone' => '08031098765',
                'patient_kin_address' => '14, Gbagada Expressway, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0013',
                'patient_lastname' => 'Musa',
                'patient_firstname' => 'Zainab',
                'patient_phone' => '08134567891',
                'patient_occupation' => 'Fashion Designer',
                'patient_religion' => 'Islam',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1991-09-16',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Integrated Healthcare Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '52, Toyin Street, Ikeja, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Musa Ibrahim',
                'kin_relationship' => 'Husband',
                'patient_kin_phone' => '08042109876',
                'patient_kin_address' => '52, Toyin Street, Ikeja, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0014',
                'patient_lastname' => 'Chukwu',
                'patient_firstname' => 'Obinna',
                'patient_phone' => '08145678902',
                'patient_occupation' => 'Architect',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1984-02-28',
                'patient_type' => 'Private',
                'patient_hmo' => null,
                'patient_nationality' => 'Nigerian',
                'patient_address' => '36, Admiralty Way, Lekki, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Chukwu Chinwe',
                'kin_relationship' => 'Spouse',
                'patient_kin_phone' => '08053210987',
                'patient_kin_address' => '36, Admiralty Way, Lekki, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0015',
                'patient_lastname' => 'Afolabi',
                'patient_firstname' => 'Temitope',
                'patient_phone' => '08156789013',
                'patient_occupation' => 'Journalist',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1989-07-11',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Premier Health Management Services',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '74, Herbert Macaulay Way, Yaba, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Afolabi Segun',
                'kin_relationship' => 'Brother',
                'patient_kin_phone' => '08064321098',
                'patient_kin_address' => '74, Herbert Macaulay Way, Yaba, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0016',
                'patient_lastname' => 'Abdullahi',
                'patient_firstname' => 'Maryam',
                'patient_phone' => '08167890124',
                'patient_occupation' => 'Medical Doctor',
                'patient_religion' => 'Islam',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1986-12-03',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Novo Health Africa',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '9, Bourdillon Road, Ikoyi, Lagos',
                'image' => null,
                'patient_kin_name' => 'Dr. Abdullahi Yusuf',
                'kin_relationship' => 'Husband',
                'patient_kin_phone' => '08075432109',
                'patient_kin_address' => '9, Bourdillon Road, Ikoyi, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0017',
                'patient_lastname' => 'Nnamdi',
                'patient_firstname' => 'Chukwuemeka',
                'patient_phone' => '08178901235',
                'patient_occupation' => 'Real Estate Developer',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1977-04-19',
                'patient_type' => 'Retainership',
                'patient_hmo' => null,
                'patient_nationality' => 'Nigerian',
                'patient_address' => '101, Ajose Adeogun Street, Victoria Island, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Nnamdi Ifeoma',
                'kin_relationship' => 'Wife',
                'patient_kin_phone' => '08086543210',
                'patient_kin_address' => '101, Ajose Adeogun Street, Victoria Island, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0018',
                'patient_lastname' => 'Adeleke',
                'patient_firstname' => 'Taiwo',
                'patient_phone' => '08189012346',
                'patient_occupation' => 'Pilot',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Male',
                'patient_status' => 'Active',
                'patient_dob' => '1983-10-27',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Reliance HMO',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '44, Ozumba Mbadiwe Avenue, Victoria Island, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mrs. Adeleke Kehinde',
                'kin_relationship' => 'Twin Sister',
                'patient_kin_phone' => '08097654321',
                'patient_kin_address' => '44, Ozumba Mbadiwe Avenue, Victoria Island, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0019',
                'patient_lastname' => 'Ogundipe',
                'patient_firstname' => 'Bukola',
                'patient_phone' => '08190123457',
                'patient_occupation' => 'Lawyer',
                'patient_religion' => 'Christianity',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1994-06-05',
                'patient_type' => 'Private',
                'patient_hmo' => null,
                'patient_nationality' => 'Nigerian',
                'patient_address' => '17, Sanusi Fafunwa Street, Victoria Island, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Ogundipe Abiodun',
                'kin_relationship' => 'Father',
                'patient_kin_phone' => '08008765432',
                'patient_kin_address' => '17, Sanusi Fafunwa Street, Victoria Island, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'card_number' => 'EMS-2024-0020',
                'patient_lastname' => 'Usman',
                'patient_firstname' => 'Fatima',
                'patient_phone' => '08101234568',
                'patient_occupation' => 'Pharmacist',
                'patient_religion' => 'Islam',
                'patient_gender' => 'Female',
                'patient_status' => 'Active',
                'patient_dob' => '1988-08-21',
                'patient_type' => 'HMO',
                'patient_hmo' => 'Medicare Health Plans Limited',
                'patient_nationality' => 'Nigerian',
                'patient_address' => '63, Ogunlana Drive, Surulere, Lagos',
                'image' => null,
                'patient_kin_name' => 'Mr. Usman Suleiman',
                'kin_relationship' => 'Husband',
                'patient_kin_phone' => '08019876543',
                'patient_kin_address' => '63, Ogunlana Drive, Surulere, Lagos',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('patients')->insert($patients);
    }
}