<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('triage_vitals', function (Blueprint $table) {
            $table->id();
            $table->foreignId('triage_queue_id')->constrained('triage_queue')->onDelete('cascade');
            $table->foreignId('patient_id')->constrained('patients')->onDelete('cascade');
            
            // DYNAMIC STAFF - Any user can record vitals
            $table->foreignId('recorded_by')->constrained('users')->onDelete('cascade');
            $table->string('recorded_by_role')->nullable()->comment('Role of staff who recorded vitals');
            
            // Vital Signs
            $table->string('blood_pressure')->nullable(); // Format: 120/80
            $table->decimal('temperature', 5, 2)->nullable(); // Celsius
            $table->integer('pulse_rate')->nullable(); // bpm
            $table->integer('respiratory_rate')->nullable(); // breaths per minute
            $table->integer('oxygen_saturation')->nullable(); // SpO2 percentage
            $table->decimal('weight', 6, 2)->nullable(); // kg
            $table->decimal('height', 5, 2)->nullable(); // cm
            $table->decimal('bmi', 5, 2)->nullable(); // Calculated
            
            // Interpretations (Auto-generated by VitalInterpreter service)
            $table->text('bp_interpretation')->nullable();
            $table->text('temp_interpretation')->nullable();
            $table->text('pulse_interpretation')->nullable();
            $table->text('rr_interpretation')->nullable();
            $table->text('spo2_interpretation')->nullable();
            $table->text('bmi_interpretation')->nullable();
            
            // Overall Assessment
            $table->enum('overall_priority', ['mild', 'moderate', 'critical'])->nullable();
            $table->json('clinical_alerts')->nullable(); // Array of critical alerts
            $table->text('notes')->nullable();
            
            $table->timestamps();
            
            // Indexes
            $table->index('overall_priority');
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('triage_vitals');
    }
};